# Generated by Django 5.2.2 on 2025-06-19 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_article_options_article_abstract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the applicant",
                        max_length=300,
                        verbose_name="Applicant Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the applicant",
                        max_length=300,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        help_text="Detailed description of the applicant's goals",
                        max_length=1200,
                        verbose_name="Applicant Goal",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("partnership", "Partnership Opportunity"),
                            ("career", "Career Opportunity"),
                            ("other", "Other"),
                        ],
                        default="general",
                        help_text="Category of the application",
                        max_length=300,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the application has been processed",
                        verbose_name="Processed Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the message sender",
                        max_length=300,
                        verbose_name="Sender Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the sender",
                        max_length=300,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Content of the message",
                        max_length=1200,
                        verbose_name="Message Content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read",
                        verbose_name="Read Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection Message",
                "verbose_name_plural": "Connection Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
