# Generated by Django 5.2.2 on 2025-06-20 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_application_connectmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Как представиться автору отзыва (например: Анна К.)",
                        max_length=100,
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        blank=True,
                        help_text="Например: ЕГЭ по биологии, 98 баллов",
                        max_length=200,
                        null=True,
                        verbose_name="Достижение/результат",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Содержание отзыва", verbose_name="Текст отзыва"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отображать ли отзыв на сайте",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Уникальная часть URL для этого отзыва",
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем больше число, тем выше отзыв в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "author_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/avatars/",
                        verbose_name="Фото автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-order", "-created_at"],
            },
        ),
    ]
