# Generated by Django 5.2.2 on 2025-06-20 21:06

import django.core.validators
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_preview",
            field=models.ImageField(
                blank=True,
                help_text="Изображение должно быть в формате JPG, PNG или WEBP.",
                null=True,
                upload_to=main.models.Article.upload_preview,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Превью статьи",
            ),
        ),
    ]
