# Generated by Django 5.2.2 on 2025-06-25 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_article_image_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The full title of the publication",
                        max_length=700,
                        verbose_name="Publication Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A URL-friendly version of the title (auto-generated)",
                        max_length=700,
                        unique=True,
                    ),
                ),
                (
                    "authors",
                    models.CharField(
                        blank=True,
                        help_text="List of authors separated by commas",
                        max_length=500,
                        verbose_name="Authors",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary or abstract of the publication",
                        max_length=2000,
                        verbose_name="Abstract/Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to the full publication",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Publication URL",
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True,
                        help_text="Name of the journal or conference where published",
                        max_length=200,
                        verbose_name="Journal/Conference",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier if available",
                        max_length=200,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        help_text="Date when the publication was released",
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured to highlight this publication",
                        verbose_name="Featured Publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-publication_date"],
                "indexes": [
                    models.Index(fields=["slug"], name="main_public_slug_82bcf3_idx"),
                    models.Index(
                        fields=["publication_date"],
                        name="main_public_publica_07720b_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="main_public_is_feat_520463_idx"
                    ),
                ],
            },
        ),
    ]
