# Generated by Django 5.2.2 on 2025-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_review_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="review",
            name="author_photo",
        ),
        migrations.AddField(
            model_name="review",
            name="author_photo_url",
            field=models.URLField(
                blank=True,
                help_text="URL аватара (Например с Google, VK, Profi.ru и т.д.)",
                max_length=500,
                null=True,
                verbose_name="Ссылка на фото автора",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="source",
            field=models.CharField(
                choices=[
                    ("unknown", "Неизвестно"),
                    ("native", "Нативный (с вашего сайта)"),
                    ("profi_ru", "Profi.ru"),
                    ("avito", "Авито"),
                    ("repetitor_ru", "Ваш репетитор"),
                    ("google", "Google Отзывы"),
                    ("yandex", "Яндекс Услуги"),
                    ("social", "Социальные сети"),
                    ("other", "Другое"),
                ],
                default="unknown",
                help_text="Откуда взят этот отзыв?",
                max_length=20,
                verbose_name="Источник отзыва",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="source_custom",
            field=models.CharField(
                blank=True,
                help_text="Например: Instagram, рекомендация друга и т.д.",
                max_length=300,
                null=True,
                verbose_name="Уточнение источника",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="source_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на отзыв"
            ),
        ),
    ]
