# Generated by Django 5.2.2 on 2025-07-11 17:10

import django.core.validators
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_tag_article_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное имя учителя",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Краткий статус под именем учителя",
                        max_length=250,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание учителя",
                        max_length=800,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение должно быть в формате JPG, PNG или WEBP. Рекомендуемый размер: 300x300px.",
                        null=True,
                        upload_to=main.models.Teacher.upload_avatar,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Электронная почта учителя",
                        max_length=300,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Контактный телефон учителя",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя в Telegram (без @)",
                        max_length=100,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "vk",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя или ID в VK",
                        max_length=100,
                        verbose_name="VK",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя в Instagram (без @)",
                        max_length=100,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя в Twitter (без @)",
                        max_length=100,
                        verbose_name="Twitter",
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True,
                        help_text="Имя пользователя или URL в LinkedIn",
                        max_length=100,
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Автоматическое поле для удобных URL",
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображается ли учитель на сайте",
                        verbose_name="Активен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
                "ordering": ["name"],
            },
        ),
    ]
