# Generated by Django 5.2.2 on 2025-07-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-star",
                        max_length=50,
                        verbose_name="Иконка (Font Awesome)",
                    ),
                ),
                ("price", models.CharField(max_length=50, verbose_name="Цена")),
                (
                    "button_text",
                    models.CharField(
                        default="Подробнее", max_length=50, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Пометка 'ВЫГОДНО'"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Текст пункта")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.lessoncard",
                    ),
                ),
            ],
        ),
    ]
