# Generated by Django 5.2.2 on 2025-07-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_lessoncard_lessonfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="lang",
            field=models.CharField(
                choices=[("ru", "Russian"), ("en", "English")],
                default="en",
                help_text="Язык для которого учитель создаётся",
                max_length=20,
                verbose_name="Язык",
            ),
        ),
    ]
