# Generated by Django 5.2.2 on 2025-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_teacher_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова для поиска",
                max_length=700,
                null=True,
                verbose_name="Кей-слова",
            ),
        ),
    ]
