# Generated by Django 5.2.2 on 2025-08-07 17:26

from django.db import migrations


def assign_reviews_to_teacher(apps, schema_editor):  # Fixed function name and parameter
    Review = apps.get_model("main", "Review")
    Teacher = apps.get_model("main", "Teacher")

    teacher = Teacher.objects.first()  # Fixed typo: "obhects" → "objects"
    if teacher:
        Review.objects.update(teacher=teacher)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_review_teacher"),  # Ensure this matches your previous migration
    ]
    operations = [
        migrations.RunPython(assign_reviews_to_teacher),  # Fixed function name
    ]
