# Generated by Django 5.2.2 on 2025-08-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_auto_20250807_1726"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        help_text="Основной тип формата (Индивидуально/Парные/Групповые/Асинхронное)",
                        max_length=50,
                        verbose_name="Тип формата",
                    ),
                ),
                (
                    "format_display",
                    models.CharField(
                        help_text="Как будет показано в таблице",
                        max_length=50,
                        verbose_name="Отображаемое название формата",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=100, verbose_name="Название программы"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Стоимость")),
                (
                    "price_unit",
                    models.CharField(
                        default="₽/час", max_length=20, verbose_name="Единица стоимости"
                    ),
                ),
                (
                    "is_group_format",
                    models.BooleanField(
                        default=False,
                        help_text="Для стилизации групповых форматов",
                        verbose_name="Групповой формат?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="main.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ["format_type", "program_name"],
                "indexes": [
                    models.Index(
                        fields=["format_type"], name="main_tariff_format__06826b_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="main_tariff_is_acti_82a94b_idx"
                    ),
                ],
            },
        ),
    ]
