# Generated by Django 5.2.2 on 2025-08-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_load_initial_tariffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Page name, displayed in footer and navbar",
                        max_length=200,
                    ),
                ),
                ("show_in_navbar", models.BooleanField(default=False)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("meta_keywords", models.CharField(blank=True, max_length=300)),
                (
                    "og_type",
                    models.CharField(blank=True, default="website", max_length=50),
                ),
                ("og_site_name", models.CharField(blank=True, max_length=100)),
                ("og_title", models.CharField(blank=True, max_length=300)),
                ("og_description", models.CharField(blank=True, max_length=500)),
                ("og_url", models.URLField(blank=True, max_length=500)),
                ("og_image", models.URLField(blank=True, max_length=500)),
                ("og_image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("og_image_height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "og_locale",
                    models.CharField(blank=True, default="en_US", max_length=10),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True, default="summary_large_image", max_length=50
                    ),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=300)),
                ("twitter_description", models.CharField(blank=True, max_length=500)),
                ("twitter_image", models.URLField(blank=True, max_length=500)),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_sub_title", models.CharField(blank=True, max_length=400)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL part after /, can be not unique",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="main.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
