# Generated by Django 5.2.2 on 2025-08-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_navbar_button",
            field=models.BooleanField(default=False),
        ),
    ]
