# Generated by Django 5.2.2 on 2025-08-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_page_is_navbar_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="config_yml",
            field=models.TextField(
                blank=True, help_text="Конфигурация страницы в формате YAML"
            ),
        ),
    ]
