# Generated by Django 5.2.2 on 2025-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_page_config_yml"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="config_yml",
            new_name="config_yaml",
        ),
        migrations.AlterField(
            model_name="page",
            name="og_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
