# Generated by Django 5.2.2 on 2025-08-26 00:33

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_rename_config_yml_page_config_yaml_alter_page_og_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="avatar2",
            field=models.ImageField(
                blank=True,
                help_text="Изображение должно быть в формате JPG, PNG или WEBP. Рекомендуемый размер: 300x300px. Аватар для страницы about.",
                null=True,
                upload_to=main.models.Teacher.upload_avatar,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Второй аватар",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="education",
            field=models.JSONField(blank=True, null=True, verbose_name="Образование"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="scientific_work",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Научная работа"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="tutoring",
            field=models.JSONField(blank=True, null=True, verbose_name="Репетиторство"),
        ),
    ]
